config/routes.rb
Rails.application.routes.draw do
  mount FaspDataSharing::Engine, at: "/"
  mount FaspBase::Engine, at: "/"

  mount MissionControl::Jobs::Engine, at: "/jobs"

  get "up" => "rails/health#show", as: :rails_health_check

  namespace :admin do
    resources :follow_recommendation_presets, only: [ :index, :create, :destroy ]
  end

  namespace :fasp do
    namespace :account_search do
      namespace :v0 do
        resource :search, only: :show
      end
    end

    namespace :follow_recommendation do
      namespace :v0 do
        resources :accounts, only: :index
      end
    end

    namespace :trends do
      namespace :v0 do
        resources :contents, only: :index, path: "content"
        resources :hashtags, only: :index
        resources :links, only: :index
      end
    end
  end

  resource :account_search, only: :show

  resources :content_trends, only: :index
  resources :hashtag_trends, only: :index
  resources :link_trends, only: :index

  root "dashboards#show"
end

app/controllers/admin/follow_recommendation_presets_controller.rb
class Admin::FollowRecommendationPresetsController < FaspBase::Admin::BaseController
  def index
    @follow_recommendation_presets = Actor.recommended
  end

  def create
    if params[:uri].present?
      CreateFollowRecommendationPresetJob.perform_later(params[:uri])

      redirect_to admin_follow_recommendation_presets_path,
        notice: t(".success")
    else
      redirect_to admin_follow_recommendation_presets_path,
        alert: t(".uri_missing")
    end
  end

  def destroy
    actor = Actor.find(params[:id])
    actor.update!(recommended: false)

    redirect_to admin_follow_recommendation_presets_path,
      notice: t(".success")
  end
end

app/views/admin/follow_recommendation_presets/index.html.erb
<div class="flex justify-between items-center">
  <%= page_header do %>
    <%= t(".follow_recommendation_presets") %>
  <% end %>
</div>

<p class="font-lg text-gray-700"><%= t(".follow_recommendation_presets_description") %></p>

<%= form_with url: admin_follow_recommendation_presets_path do |f| %>
  <div class="flex gap-2">
    <%= f.url_field :uri, placeholder: t(".uri_placeholder") %>
    <%= button type: :submit do %>
      <%= t(".add_account") %>
    <% end %>
  </div>
<% end %>

<table>
  <thead>
    <tr>
      <th><%= Actor.human_attribute_name(:uri) %></th>
      <th><%= Actor.human_attribute_name(:discoverable) %></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @follow_recommendation_presets.each do |actor| %>
      <tr class="even:bg-blue-50">
        <%= td do %><%= actor.uri %><% end %>
        <%= td do %><% if actor.discoverable? %>&check;<% end %><% end %>
        <%= td do %>
          <%= action_link_to t(".delete"), admin_follow_recommendation_preset_path(actor), data: {turbo_method: :delete} %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>